export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS';
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';
export const OBTENER_PRODUCTOS_ERROR = 'OBTENER_PRODUCTOS_ERROR';

export const OBTENER_USERINFO = 'OBTENER_USERINFO';
export const OBTENER_USERINFO_EXITO = 'OBTENER_USERINFO_EXITO';
export const OBTENER_USERINFO_ERROR = 'OBTENER_USERINFO_ERROR';

export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const SELECCIONAR_PRODUCTO_EXITO = 'SELECCIONAR_PRODUCTO_EXITO';
export const SELECCIONAR_PRODUCTO_ERROR = 'SELECCIONAR_PRODUCTO_ERROR';

export const CONFIRMAR_COMPRA = 'CONFIRMAR_COMPRA';
export const CONFIRMAR_COMPRA_EXITO = 'CONFIRMAR_COMPRA_EXITO';
export const CONFIRMAR_COMPRA_ERROR = 'CONFIRMAR_COMPRA_ERROR';

export const REFILL_PUNTOS = 'REFILL_PUNTOS';
export const REFULL_PUNTOS_EXITO = 'REFULL_PUNTOS_EXITO';
export const REFILL_PUNTOS_ERROR = 'REFILL_PUNTOS_ERROR';

export const MOSTRAR_HISTORIAL = 'MOSTRAR_HISTORIAL';
export const MOSTRAR_HISTORIAL_EXITO = 'MOSTRAR_HISTORIAL_EXITO';
export const MOSTRAR_HISTORIAL_ERROR = 'MOSTRAR_HISTORIAL_ERROR';